// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e20beb50-33ea-411e-9782-d11336b8b2d1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RWqabwLyS",
    "aws_user_pools_web_client_id": "62475soocjgccsneb83g78biv0",
    "aws_appsync_graphqlEndpoint": "https://zp5vonnjdza5xezllxyr23tyuy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
